---
- name: Install applications
  environment:
    PATH: /usr/local/bin:{{ ansible_env["PATH"] }}
  homebrew:
    name: '{{ apps }}'
    state: latest
  # with_items: '{{ apps }}'
  become: no
  # notify:
  # - restart dock