---
- name: Make sure Homebrew directories exists
  file: 
    path: /usr/local/*
    state: directory
    mode: 0775
    owner: root
    group: wheel
    recurse: yes
  become: yes

- name: Download Homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: /tmp/install

- name: Install Homebrew
  shell: /usr/bin/ruby /tmp/install < /dev/null
# 🎉 https://stackoverflow.com/a/39864317/503463

- name: Update Homebrew (first try may fail)
  homebrew: update_homebrew=yes
  become: no
  ignore_errors: yes

- name: Update Homebrew
  homebrew: update_homebrew=yes
  become: no


